### ISSUE TITLE
Make crypto algorithm configurable

### ISSUE THREAD

**Issue by jokimaki** [metosin/maailma#3]
I would suggest using a modern algorithm such as AES-256 instead of 3DES. In order to maintain backwards compatibility the algorithm name could be passed as an optional parameter along with the secret key.

**Comment by Deraen** [comment]
Might be good idea to store the used algorithm as part of the encrypted value? `#ENC algorithm;data` or something. Then the EDN can contain values encrypted using different algorithms.

**Comment by jokimaki** [comment]
Storing the algorithm in the EDN file would certainly ease the transition to a new algorithm, there would be no need at all to change the client code.
